use_frameworks!

platform :ios, '9.0'

target 'RCCoreKit_Example' do
  pod 'RCCoreKit', :path => '../'

  target 'RCCoreKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
